spring:
  application:
    name: RSC-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/deepkumar19970/microservices_repo
          username: deepkumar19970
          password: pNfMgMHQSXKRy7@

server:
  port: 8083

