spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/RSCBilling
  config:
    import: http://localhost:8083/
  application:
    name: RSC-API-GATEWAY
eureka:
  instance:
    prefer-ip-address: true
    hostname: RSC-API-GATEWAY

  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084


jwt:
  secret: GATEWAY